# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  log-level:
    description: |
      Configures the log level.
    default: "info"
    type: string
  authorized-users:
    description: |
      Comma separed list of authorized users. By default all users are authorized.
    default: "*"
    type: string