# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  log_level:
    description: |
      Configures the log level. 

      Acceptable values are: "info", "debug", "warning", "error" and "critical"
    default: "info"
    type: string
  s3_access_key:
    description: |
      S3 access key
    default: ""
    type: string
  s3_secret_key:
    description: |
      S3 secret key
    default: ""
    type: string
  s3_endpoint:
    description: |
      S3 instance endpoint
    default: ""
    type: string
  spark_logs_s3_dir:
    description: |
      S3 directory for Spark logs
    default: ""
    type: string
  s3_credentials_provider:
    description: |
      S3 credentials provider class to be used
    default: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    type: string
  s3_ssl_enabled:
    description: |
      Boolean to indicate if SSL is enabled for the S3 connection
    default: False
    type: boolean
