# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

[tool.poetry]
package-mode = false
requires-poetry = ">=2.0.0"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
ops = "^3.7.1"
pydantic = "^2.13.4"
pyyaml = ">=6.0.3"
boto3 = "^1.43.25"
jsonschema = "^4.26.0"
tenacity = ">=9.1.4"
azure-storage-blob = "^12.30.0"
object-storage-charmlib = "^1.0.0"

[tool.poetry.group.charm-libs.dependencies]
ops = "^3.0.0"
poetry-core = "*"
# grafana_agent/v0/cos_agent.py requires pydantic <2
# traefix_k8s/v2/ingress.py
pydantic = "^1.10.17, <2"
# grafana_agent/v0/cos_agent.py
# loki_k8s/v1/loki_push_api.py
# prometheus_k8s/v0/prometheus_scrape.py
pyyaml = "*"
# oauth2_proxy_k8s/v0/auth_proxy.py
jsonschema = "*"
# loki_k8s/v1/loki_push_api.py
# prometheus_k8s/v0/prometheus_scrape.py
cosl = "*"

[tool.poetry.group.format]
optional = true

[tool.poetry.group.format.dependencies]
ruff = ">=0.15.16"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
ruff = ">=0.15.16"
codespell = ">=2.4.2"
mypy = "^2.3.0"
boto3-stubs = { extras = ["s3"], version = "^1.43.25" }
types-pyyaml = "^6.0.12.20250915"
types-requests = "^2.32.4.20260107"

[tool.poetry.group.unit]
optional = true

[tool.poetry.group.unit.dependencies]
pytest = "^9.0.3"
coverage = { extras = ["toml"], version = ">7.0" }
ops = { version = "^3.7.1", extras = ["testing"] }
moto = { extras = ["s3"], version = "^5.2.2" }

[tool.poetry.group.integration]
optional = true

[tool.poetry.group.integration.dependencies]
pytest = "^9.0.3"
coverage = { extras = ["toml"], version = ">7.0" }
tenacity = "^9.1.4"
jubilant = "^1.10.0"
python-dotenv = "^1.2.2"
pytest-playwright = "^0.8.0"
lightkube = "^0.21.0"
jinja2 = "*"

[tool.ruff]
line-length = 99
extend-exclude = ["__pycache__", "*.egg_info"]
target-version = "py310"
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E", "W", "F", "C", "N", "D", "I001"]
extend-ignore = [
  "D203",
  "D204",
  "D213",
  "D215",
  "D400",
  "D401",
  "D404",
  "D406",
  "D407",
  "D408",
  "D409",
  "D413",
]
ignore = ["E501", "D107"]
per-file-ignores = { "tests/*" = ["D100", "D101", "D102", "D103", "D104", "E999"], "src/literals.py" = ["D101"], "src/*/__init__.py" = ["D104"] }
mccabe.max-complexity = 10

[tool.mypy]
exclude = [
  "lib",
]
follow_imports = "silent"

[[tool.mypy.overrides]]
module = [
  "charms.data_platform_libs.*",
  "charms.grafana_k8s.*",
  "charms.loki_k8s.*",
  "charms.prometheus_k8s.*",
  "charms.tls_certificates_interface.*",
  "charms.oauth2_proxy_k8s.*",
  "charms.oathkeeper.*",
  "charms.traefik_k8s.*",
]
ignore_missing_imports = true

# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
markers = ["unstable"]

[tool.pyright]
include = ["src"]
extraPaths = ["./lib", "src"]
pythonVersion = "3.10"
pythonPlatform = "All"
