name: Spark History Server Testing
on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit

  integration-test:
    name: Integration tests (microk8s)
    timeout-minutes: 120
    needs:
      - lint
      - unit-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=minioadmin" \
                     -e "MINIO_SECRET_KEY=minioadmin" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data

          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set myminio/ http://127.0.0.1:9000 minioadmin minioadmin
          ./mc mb myminio/history-server
          ./mc mb myminio/history-server/spark-events
          ./mc mb myminio/history-server/spark-events-2
          ./mc mb myminio/history-server/spark-events-3
          ./mc ls myminio
          export CONTAINER_ID=$(docker ps -n 1 | tail -n 1 | cut -d' ' -f1)
          export CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
          echo "MINIO_CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
          echo "MINIO_CONTAINER_IP=$CONTAINER_IP" >> $GITHUB_ENV
          echo "minio container ${{ env.MINIO_CONTAINER_ID }} launched with ip ${{ env.MINIO_CONTAINER_IP }}"

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          bootstrap-options: "--agent-version 2.9.29"
      - name: Run integration tests
        run: tox -e integration
        env:
          MINIO_CONTAINER_ID : ${{ env.MINIO_CONTAINER_ID }}
          MINIO_CONTAINER_IP : ${{ env.MINIO_CONTAINER_IP }}