name: Release to charmhub

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  build:
    name: Build charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v26.0.0
    with:
      cache: false

  publish:
    name: Release charm
    needs:
      - ci-tests
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@v26.0.0
    with:
      channel: 3.4/edge
      artifact-name: ${{ needs.build.outputs.artifact-name }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write  # Needed to create GitHub release
